trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesServiceConnection: 'kubernetesServiceConnection'  # Replace with your service connection name
  namespace: 'default'  # Or another namespace if you prefer

stages:
- stage: Deploy
  jobs:
  - job: DeployNGINX
    displayName: 'Deploy NGINX to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
        namespace: '$(namespace)'
        command: 'apply'
        useConfigurationFile: false
        arguments: '-f - --v=8'
        configuration: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: nginx
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
        namespace: '$(namespace)'
        command: 'apply'
        useConfigurationFile: false
        arguments: '-f - --v=8'
        configuration: |
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            labels:
              app: nginx
          spec:
            selector:
              app: nginx
            ports:
            - protocol: TCP
        
